#!/bin/bash

kill $(ps U $UID | awk '/scripts/&&/status/' | grep -vi "$$\|grep\|awk" | awk '{print $1}')

#colors
purple="#b6848b"
cyan="#c5c5c5"
red="#9693b5"


# date/time section
dte(){
    dte="$(date +"%a %d/%m")"
    tme="$(date +"%H:%M")"
#    echo "^s[right;$red;$dte ] ^s[right;$cyan;$tme]"    
    echo "^s[right;$red;$dte ] ^s[right;$cyan;$tme ](1;spawn;~/scripts/stats/dzen_date.sh)"

}

# power
pwr(){
    pwrsta="$(cat /sys/class/power_supply/BAT0/status | cut -c 1)"
    pwrperc="$(awk 'sub(/,/,"") {print $4}' <(acpi -b) | cut -d , -f 1 $1)"
    if [ "$pwrsta" == "F" ]; then
        pwr="charged"
    else
        pwr="$pwrperc"
    fi
#    echo "^s[right;$red;bat ]^s[right;$cyan;$pwr ]"    
   echo "^s[right;$red;bat ]^s[right;$cyan;$pwr ](1;spawn;~/scripts/stats/dzen_bat.sh)"

}


np(){
if [ "`mpc 2>&1 | wc -l`" -gt "1" ]; then
   if [ "`mpc | grep "^\[paused\]"`" != "" ]; then
        mpd_current="paused"
    else
        mpd_current=`mpc current`
    fi
else
    mpd_current="none"
fi
#echo "^s[right;$red;$echo mpd ]^s[right;$cyan;$mpd_current ]"
echo "^s[right;$red;$echo mpd ]^s[right;$cyan;$mpd_current ](1;spawn;~/scripts/stats/dzen_music.sh)"

}

sep(){
    echo "^s[right;$purple;::: ]"
} 

TIMING=1
 
statustext()
{
     wmfs -c status "sonsky $(np) $(sep) $(pwr) $(sep) $(dte)" #$(tme)"
}
 

while true ; do
    statustext
    sleep $TIMING
done
