#!/bin/bash

kill $(ps U $UID | awk '/scripts/&&/status/' | grep -vi "$$\|grep\|awk" | awk '{print $1}')

#colors
#clear="#fdddef"
cyan="#8478a1"
red="#ed8c59"


# date/time section
dte(){
    dte="$(date +"%a %d/%m")"
    echo "^s[right;$red;$dte ]"
}


tme(){
    tme="$(date +"%H:%M")"
    echo "^s[right;$cyan;$tme ]"
}


# power
pwr(){
    pwrsta="$(cat /sys/class/power_supply/BAT0/status | cut -c 1)"
    pwrperc="$(awk 'sub(/,/,"") {print $4}' <(acpi -b) | cut -d , -f 1 $1)"
    if [ "$pwrsta" == "F" ]; then
        pwr="charged"
    else
        pwr="$pwrperc"
    fi
    echo "^s[right;$red;bat ]^s[right;$cyan;$pwr  ]"
}


np(){
if [ "`mpc 2>&1 | wc -l`" -gt "1" ]; then
    if [ "`mpc | grep "^\[paused\]"`" != "" ]; then
        mpd_current="paused"
    else
        mpd_current=`mpc current`
    fi
else
    mpd_current="none"
fi
echo "^s[right;$red;$echo mpd ]^s[right;$cyan;$mpd_current  ]"
}

 
TIMING=1
 
statustext()
{
     wmfs -c status "sonsky $(np) $(pwr) $(dte) $(tme)"
}
 

while true ; do
    statustext
    sleep $TIMING
done
